import { Inter } from '@next/font/google';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Página Inicial</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="relative flex flex-col justify-center items-center">
          <p className="text-2xl font-bold text-center">
            Para onde deseja ir:
          </p>
        </div>

        <div className={styles.grid}>
          <Link
            href="/login"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Entrar <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Entre para acessar o sistema
            </p>
          </Link>

          <Link
            href="/registro"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Registro <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Criar uma conta
            </p>
          </Link>

          <Link
            href="/recover"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Recuperar de senha <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Recupere sua senha
            </p>
          </Link>

          <Link
            href="/dashboard"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Painel Principal <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Acesse o Painel Principal para analisar seus dados
            </p>
          </Link>
        </div>
      </main>
    </>
  );
}